"""Hermetic unit tests for the binwalk sample generator.

No Docker/root/binwalk needed: operates on the generated bytes in memory and
asserts determinism plus the presence and validity of the embedded formats that
`binwalk -e` is meant to detect and extract.
"""

from __future__ import annotations

import bz2
import importlib.util
import io
import lzma
import sys
import unittest
import zipfile
import zlib
from pathlib import Path

# Load the generator module by path (the script has no package). It must be
# registered in sys.modules before exec so its @dataclass decorators can resolve
# their own module.
_SPEC = importlib.util.spec_from_file_location(
    "gen_binwalk_samples", Path(__file__).resolve().parent / "gen_binwalk_samples.py"
)
gen = importlib.util.module_from_spec(_SPEC)
assert _SPEC and _SPEC.loader
sys.modules[_SPEC.name] = gen
_SPEC.loader.exec_module(gen)

EXTRACTABLE_MAGICS = {
    "gzip": b"\x1f\x8b",
    "bzip2": b"BZh",
    "xz": b"\xfd7zXZ\x00",
    "zip": b"PK\x03\x04",
    "tar": b"ustar",
    "cpio": b"070701",
}
IDENTIFIABLE_MAGICS = {
    "png": b"\x89PNG\r\n\x1a\n",
    "jpeg": b"\xff\xd8\xff",
    "gif": b"GIF89a",
    "elf": b"\x7fELF",
    "uimage": bytes.fromhex("27051956"),
}


class GenBinwalkSamplesTest(unittest.TestCase):
    def test_composite_is_deterministic(self) -> None:
        a = gen.build_composite(2 * 1024 * 1024)
        b = gen.build_composite(2 * 1024 * 1024)
        self.assertEqual(a.data, b.data, "composite must be byte-identical across runs")

    def test_composite_reaches_target_size(self) -> None:
        size = 3 * 1024 * 1024
        self.assertEqual(len(gen.build_composite(size).data), size)

    def test_composite_embeds_all_formats(self) -> None:
        data = gen.build_composite(2 * 1024 * 1024).data
        for name, magic in {**EXTRACTABLE_MAGICS, **IDENTIFIABLE_MAGICS}.items():
            self.assertIn(magic, data, f"composite is missing the {name} signature")

    def test_embedded_streams_actually_decompress(self) -> None:
        # binwalk -e succeeds only if the carved streams are valid, not just the magic.
        data = gen.build_composite(2 * 1024 * 1024).data

        gz = zlib.decompressobj(16 + zlib.MAX_WBITS).decompress(data[data.find(b"\x1f\x8b") :])
        self.assertGreater(len(gz), 0)
        self.assertGreater(len(bz2.BZ2Decompressor().decompress(data[data.find(b"BZh") :])), 0)
        self.assertGreater(
            len(lzma.LZMADecompressor().decompress(data[data.find(b"\xfd7zXZ\x00") :])), 0
        )

    def test_zip_recurses_into_nested_gzip(self) -> None:
        data = gen.build_composite(2 * 1024 * 1024).data
        start = data.find(b"PK\x03\x04")
        end = data.rfind(b"PK\x05\x06") + 22
        names = zipfile.ZipFile(io.BytesIO(data[start:end])).namelist()
        self.assertIn("etc/banner.gz", names, "zip should contain a nested gzip for recursive extraction")

    def test_single_format_samples_have_expected_magic(self) -> None:
        by_name = {s.name: s for s in gen.build_single_format_samples()}
        self.assertTrue(by_name["gzip-stream.bin"].data.startswith(b"\x1f\x8b"))
        self.assertTrue(by_name["bzip2-stream.bin"].data.startswith(b"BZh"))
        self.assertTrue(by_name["xz-stream.bin"].data.startswith(b"\xfd7zXZ\x00"))
        self.assertTrue(by_name["zip-archive.bin"].data.startswith(b"PK\x03\x04"))


if __name__ == "__main__":
    unittest.main()
